# Generated by Django 4.0.1 on 2022-01-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notication',
            name='casee',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='notication',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(to='shopapp.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(upload_to='img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(to='shopapp.Product'),
        ),
    ]
