# Generated by Django 4.0.1 on 2022-01-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(blank=True, null=True, to='shopapp.Product'),
        ),
    ]
