# Generated by Django 4.0.1 on 2022-01-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_notication_casee_notication_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='product_ratings', to='shopapp.Product'),
        ),
    ]
